DROP TABLE IF EXISTS bookmarks;

CREATE TABLE bookmarks (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  rating int NOT NULL,
  description TEXT,
  CHECK(
    rating BETWEEN 1
    AND 5
  )
);